import { Region } from '../types';

const PREFECTURE_TO_REGION: Record<string, Region> = {
  Hokkaido: 'hokkaido_tohoku',
  Aomori: 'hokkaido_tohoku',
  Iwate: 'hokkaido_tohoku',
  Miyagi: 'hokkaido_tohoku',
  Akita: 'hokkaido_tohoku',
  Yamagata: 'hokkaido_tohoku',
  Fukushima: 'hokkaido_tohoku',
  Ibaraki: 'kanto',
  Tochigi: 'kanto',
  Gunma: 'kanto',
  Saitama: 'kanto',
  Chiba: 'kanto',
  Tokyo: 'kanto',
  Kanagawa: 'kanto',
  Niigata: 'chubu',
  Toyama: 'chubu',
  Ishikawa: 'chubu',
  Fukui: 'chubu',
  Yamanashi: 'chubu',
  Nagano: 'chubu',
  Gifu: 'chubu',
  Shizuoka: 'chubu',
  Aichi: 'chubu',
  Mie: 'kinki',
  Shiga: 'kinki',
  Kyoto: 'kinki',
  Osaka: 'kinki',
  Hyogo: 'kinki',
  Nara: 'kinki',
  Wakayama: 'kinki',
  Tottori: 'chugoku',
  Shimane: 'chugoku',
  Okayama: 'chugoku',
  Hiroshima: 'chugoku',
  Yamaguchi: 'chugoku',
  Tokushima: 'shikoku',
  Kagawa: 'shikoku',
  Ehime: 'shikoku',
  Kochi: 'shikoku',
  Fukuoka: 'kyushu',
  Saga: 'kyushu',
  Nagasaki: 'kyushu',
  Kumamoto: 'kyushu',
  Oita: 'kyushu',
  Miyazaki: 'kyushu',
  Kagoshima: 'kyushu',
  Okinawa: 'okinawa',
};

export function prefectureToRegion(prefecture: string): Region {
  return PREFECTURE_TO_REGION[prefecture] ?? 'kanto';
}
